/**
 * Deployment renderers. Translates a resolved `DeploySpec` into a concrete
 * deployment for the instance:
 *
 *   in-gateway → multi-tenant: the business already lives in this gateway's
 *                workspace; we flip its manifest to active and bind channels.
 *   container  → render a per-instance docker-compose + env file for an
 *                isolated gateway, written to businesses/<id>/deploy/.
 *   cloud      → render a per-instance fly.toml or render.yaml with a unique
 *                app name + generated gateway token + state volume.
 *
 * Cloud/container targets produce *artifacts and an apply command* rather than
 * shelling out: the gateway process typically lacks Fly/Docker credentials and
 * outbound provisioning rights. The harness (or an operator) runs the returned
 * command. This keeps provisioning deterministic and side-effect-free here.
 */

import { randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { DeploySpec } from "./types.js";

export interface DeployOutcome {
  target: DeploySpec["target"];
  /** Files written under businesses/<id>/deploy/, relative to that dir. */
  artifacts: string[];
  /** Command for the harness/operator to run (cloud/container only). */
  apply_command?: string;
  /** Generated gateway bearer token (cloud/container only). Surfaced once. */
  gateway_token?: string;
  /** Base URL the harness can reach the new gateway at (cloud only, post-apply). */
  base_url?: string;
  notes: string[];
}

async function writeArtifact(dir: string, name: string, content: string): Promise<string> {
  const path = join(dir, name);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf-8");
  return name;
}

async function patchManifestStatus(businessDir: string, status: string): Promise<void> {
  const path = join(businessDir, "manifest.json");
  const manifest = JSON.parse(await readFile(path, "utf-8")) as Record<string, unknown>;
  manifest.status = status;
  manifest.deployed_at = new Date().toISOString();
  await writeFile(path, JSON.stringify(manifest, null, 2), "utf-8");
}

function renderComposeYaml(instanceId: string, token: string): string {
  return `# Generated by MABOS provisioning for instance "${instanceId}".
services:
  mabos-${instanceId}:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    command: node dist/index.js gateway --port 18789 --bind lan
    environment:
      OPENCLAW_GATEWAY_TOKEN: "${token}"
      OPENCLAW_STATE_DIR: /data/.openclaw
      OPENCLAW_WORKSPACE_DIR: /data/workspace
      MABOS_INSTANCE_ID: "${instanceId}"
    ports:
      - "18789"
    volumes:
      - mabos-${instanceId}-data:/data
volumes:
  mabos-${instanceId}-data:
`;
}

function renderFlyToml(instanceId: string, region: string): string {
  return `# Generated by MABOS provisioning for instance "${instanceId}".
app = "mabos-${instanceId}"
primary_region = "${region}"

[build]
dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"
OPENCLAW_STATE_DIR = "/data"
MABOS_INSTANCE_ID = "${instanceId}"
NODE_OPTIONS = "--max-old-space-size=1536"

[processes]
app = "node dist/index.js gateway --port 3000 --bind lan"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
size = "shared-cpu-2x"
memory = "2048mb"

[mounts]
source = "mabos_${instanceId}_data"
destination = "/data"
`;
}

function renderRenderYaml(instanceId: string): string {
  return `# Generated by MABOS provisioning for instance "${instanceId}".
services:
  - type: web
    name: mabos-${instanceId}
    runtime: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8080"
      - key: OPENCLAW_STATE_DIR
        value: /data/.openclaw
      - key: OPENCLAW_WORKSPACE_DIR
        value: /data/workspace
      - key: MABOS_INSTANCE_ID
        value: "${instanceId}"
      - key: OPENCLAW_GATEWAY_TOKEN
        generateValue: true
    disk:
      name: mabos-${instanceId}-data
      mountPath: /data
      sizeGB: 1
`;
}

/** Execute the resolved deploy spec for an instance. */
export async function runDeploy(params: {
  businessDir: string;
  instanceId: string;
  deploy: DeploySpec;
}): Promise<DeployOutcome> {
  const { businessDir, instanceId, deploy } = params;
  const deployDir = join(businessDir, "deploy");
  const notes: string[] = [];

  if (deploy.target === "in-gateway") {
    if (deploy.activate ?? true) {
      await patchManifestStatus(businessDir, "active");
      notes.push("Instance marked active in this gateway.");
    } else {
      notes.push("Instance scaffolded but left inactive (activate=false).");
    }
    if (deploy.channels?.length) {
      notes.push(`Channels requested: ${deploy.channels.join(", ")} (bind via gateway config).`);
    }
    return { target: "in-gateway", artifacts: [], notes };
  }

  if (deploy.target === "container") {
    const token = `mabos-${randomUUID()}`;
    const artifacts = [
      await writeArtifact(deployDir, "docker-compose.yml", renderComposeYaml(instanceId, token)),
    ];
    notes.push("Isolated container gateway config rendered. Run the apply command to start it.");
    return {
      target: "container",
      artifacts,
      gateway_token: token,
      apply_command: `docker compose -f businesses/${instanceId}/deploy/docker-compose.yml up -d`,
      notes,
    };
  }

  // cloud
  const provider = deploy.provider ?? "fly";
  const region = deploy.region ?? "iad";
  const artifacts: string[] = [];
  let applyCommand: string;
  let token: string | undefined;

  if (provider === "fly") {
    token = `mabos-${randomUUID()}`;
    artifacts.push(await writeArtifact(deployDir, "fly.toml", renderFlyToml(instanceId, region)));
    applyCommand =
      `fly launch --copy-config --no-deploy -c businesses/${instanceId}/deploy/fly.toml && ` +
      `fly secrets set OPENCLAW_GATEWAY_TOKEN=${token} -a mabos-${instanceId} && ` +
      `fly deploy -c businesses/${instanceId}/deploy/fly.toml`;
    notes.push(`Fly app "mabos-${instanceId}" config rendered (region ${region}).`);
  } else {
    artifacts.push(await writeArtifact(deployDir, "render.yaml", renderRenderYaml(instanceId)));
    applyCommand = `render blueprint launch businesses/${instanceId}/deploy/render.yaml`;
    notes.push(
      `Render service "mabos-${instanceId}" config rendered; token is generated by Render.`,
    );
  }

  return {
    target: "cloud",
    artifacts,
    gateway_token: token,
    apply_command: applyCommand,
    base_url: provider === "fly" ? `https://mabos-${instanceId}.fly.dev` : undefined,
    notes,
  };
}
